### ISSUE TITLE
Refactor: Header of standardized .csv dataset files

### ISSUE THREAD

**Issue by AlvaroJoseLopes** [AKSW/frankgraphbench#10]
**Currently behaviour:**
The user needs to indicate if the column feature is a list of properties with the directive `grouped`.
Example:
```yaml
....
enrich:
      map_path: datasets/ml-100k/processed/map.csv
      enrich_path: datasets/ml-100k/processed/enriched.csv
      remove_unmatched: False
      properties:
        - type: subject
          grouped: True
          sep: "::"
        - type: director
          grouped: True
          sep: "::"
```
Problems: 
* The user would need to indicate this for all features. However the user doesn't need to know in advance if the feature is a list of properties.
* The user should be able to set the features that they want to add to the pipeline only by their name, without requiring any extra information.

**Proposed Solution:**
Use a new Header standard that indicates the feature name and its type, such as `column_name::type`.  Example of .csv header:
```csv
item_id::string, abstract::string, producer::string_list, distributor::string_list,
```
Pros:
* This allows the Dataloader to know in advance the feature type and perform the proper processing method.
* The user only needs to specify the feature names on the config file

The example above following the new standard:
```
enrich:
      map_path: datasets/ml-100k/processed/map.csv
      enrich_path: datasets/ml-100k/processed/enriched.csv
      remove_unmatched: False
      properties: [subject, director]
```

Currently types allowed:
- *string*
- *string_list*, separated by "::"
- *number*
